/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ocxrst;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Maria Luisa Martinez
 */
public class INVENTARIOS extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(INVENTARIOS.class.getName());
    private static final String INVENTARIOS_FILE_ABSOLUTE = "C:\\OCXRST\\OrdendeComprasRST\\src\\main\\java\\com\\mycompany\\ocxrst\\BASES\\INVENTARIOS.xlsx";
    private static final String INVENTARIOS_FILE_RELATIVE = "src\\main\\java\\com\\mycompany\\ocxrst\\BASES\\INVENTARIOS.xlsx";
    private static final String[] ENCABEZADOS = {
        "CODIGO", "DESCRIPCION", "UNIDAD", "PRECIO_UNITARIO", "CANTIDAD", "ACTIVO"
    };
    private static final DataFormatter DATA_FORMATTER = new DataFormatter();
    private int filaInventarioActual = -1;

    /**
     * Creates new form PRINCIPAL
     */
    public INVENTARIOS() {
        initComponents();
        IconoVentanaUtil.aplicar(this);
        setLocationRelativeTo(null);
        asegurarArchivoInventarios();
        configurarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 95, 131));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVENTARIOS");

        jButton1.setBackground(new java.awt.Color(0, 95, 131));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CREAR");

        jButton2.setBackground(new java.awt.Color(0, 95, 131));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDITAR");

        jButton3.setBackground(new java.awt.Color(0, 95, 131));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ELIMINAR");

        jButton6.setBackground(new java.awt.Color(0, 95, 131));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("< ATRAS");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jLabel2.setText("DESCRIPCIÓN:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("UNIDAD:");

        jLabel4.setText("PRECIO UNITARIO:");

        jLabel6.setText("CÓDIGO:");

        jLabel7.setText("CANTIDAD: ");

        jButton4.setBackground(new java.awt.Color(0, 95, 131));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BUSCAR");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        PRINCIPAL ventana = new PRINCIPAL();
        ventana.setVisible(true); // 👉 abre la nueva ventana
        
        this.dispose(); // 👉 cierra el login
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        buscarInventario();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new INVENTARIOS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    private void configurarEventos() {
        jButton1.addActionListener(e -> crearInventario());
        jButton2.addActionListener(e -> editarInventario());
        jButton3.addActionListener(e -> alternarEstadoInventario());
        restablecerIndicadorEstado();
    }//configurarEventos

    private void asegurarArchivoInventarios() {
        File archivo = obtenerArchivoInventarios();
        if (!archivo.exists()) {
            try (Workbook libro = new XSSFWorkbook()) {
                Sheet hoja = libro.createSheet("INVENTARIOS");
                asegurarEncabezados(hoja);
                guardarLibro(libro, archivo);
            } catch (IOException ex) {
                mostrarError("No se pudo crear el archivo de inventarios.", ex);
            }
            return;
        }

        try (Workbook libro = cargarLibro(archivo)) {
            Sheet hoja = obtenerHojaInventarios(libro);
            if (asegurarEncabezados(hoja)) {
                guardarLibro(libro, archivo);
            }
        } catch (IOException ex) {
            mostrarError("No se pudo preparar el archivo de inventarios.", ex);
        }
    }//asegurarArchivoInventarios

    private void crearInventario() {
        if (!validarCamposBase()) {
            return;
        }

        String codigo = jTextField1.getText().trim();

        try {
            File archivo = obtenerArchivoInventarios();
            try (Workbook libro = cargarLibro(archivo)) {
                Sheet hoja = obtenerHojaInventarios(libro);
                asegurarEncabezados(hoja);

                if (buscarFilaPorCodigo(hoja, codigo) >= 0) {
                    JOptionPane.showMessageDialog(this, "Ya existe un inventario con ese CODIGO.");
                    return;
                }

                int nuevaFila = primeraFilaDisponible(hoja);
                Row fila = hoja.getRow(nuevaFila);
                if (fila == null) {
                    fila = hoja.createRow(nuevaFila);
                }

                guardarDatosEnFila(fila);
                escribirCelda(fila, 5, "1");

                guardarLibro(libro, archivo);
                filaInventarioActual = nuevaFila;
                actualizarIndicadorEstado("1");
            }

            JOptionPane.showMessageDialog(this, "Inventario creado.\nCODIGO: " + codigo + "\nEstado: ACTIVO (1)");
            limpiarFormulario(false);
        } catch (IOException ex) {
            mostrarError("No se pudo crear el inventario.", ex);
        }
    }//crearInventario

    private void editarInventario() {
        if (!validarCamposBase()) {
            return;
        }

        try {
            File archivo = obtenerArchivoInventarios();
            try (Workbook libro = cargarLibro(archivo)) {
                Sheet hoja = obtenerHojaInventarios(libro);
                asegurarEncabezados(hoja);

                int filaIndex = resolverFilaInventario(hoja);
                if (filaIndex < 0) {
                    restablecerIndicadorEstado();
                    JOptionPane.showMessageDialog(this, "No se encontro un inventario para editar. Usa BUSCAR primero.");
                    return;
                }

                String codigoForm = jTextField1.getText().trim();
                int filaMismoCodigo = buscarFilaPorCodigo(hoja, codigoForm);
                if (filaMismoCodigo >= 0 && filaMismoCodigo != filaIndex) {
                    JOptionPane.showMessageDialog(this, "El CODIGO ya pertenece a otro inventario.");
                    return;
                }

                Row fila = hoja.getRow(filaIndex);
                if (fila == null) {
                    fila = hoja.createRow(filaIndex);
                }

                guardarDatosEnFila(fila);

                if (leerCelda(fila, 5).isEmpty()) {
                    escribirCelda(fila, 5, "1");
                } else {
                    escribirCelda(fila, 5, normalizarEstado(leerCelda(fila, 5)));
                }

                guardarLibro(libro, archivo);
                filaInventarioActual = filaIndex;
                actualizarIndicadorEstado(leerCelda(fila, 5));
            }

            JOptionPane.showMessageDialog(this, "Inventario actualizado correctamente.");
        } catch (IOException ex) {
            mostrarError("No se pudo editar el inventario.", ex);
        }
    }//editarInventario

    private void alternarEstadoInventario() {
        try {
            File archivo = obtenerArchivoInventarios();
            try (Workbook libro = cargarLibro(archivo)) {
                Sheet hoja = obtenerHojaInventarios(libro);
                asegurarEncabezados(hoja);

                int filaIndex = resolverFilaInventario(hoja);
                if (filaIndex < 0) {
                    restablecerIndicadorEstado();
                    JOptionPane.showMessageDialog(this, "No se encontro un inventario para activar/desactivar. Usa BUSCAR primero.");
                    return;
                }

                Row fila = hoja.getRow(filaIndex);
                if (fila == null) {
                    restablecerIndicadorEstado();
                    JOptionPane.showMessageDialog(this, "El registro encontrado esta vacio.");
                    return;
                }

                String estadoActual = normalizarEstado(leerCelda(fila, 5));
                String nuevoEstado = "1".equals(estadoActual) ? "0" : "1";
                escribirCelda(fila, 5, nuevoEstado);

                guardarLibro(libro, archivo);
                actualizarIndicadorEstado(nuevoEstado);
                filaInventarioActual = filaIndex;

                String codigo = leerCelda(fila, 0);
                String mensajeEstado = "1".equals(nuevoEstado) ? "ACTIVADO (1)" : "DESACTIVADO (0)";
                JOptionPane.showMessageDialog(this, "Inventario actualizado:\nCodigo: " + codigo + "\nEstado: " + mensajeEstado);
            }
        } catch (IOException ex) {
            mostrarError("No se pudo cambiar el estado del inventario.", ex);
        }
    }//alternarEstadoInventario

    private void buscarInventario() {
        String codigo = jTextField1.getText().trim();
        String descripcion = jTextField2.getText().trim();

        if (codigo.isEmpty() && descripcion.isEmpty()) {
            restablecerIndicadorEstado();
            JOptionPane.showMessageDialog(this, "Ingresa CODIGO o DESCRIPCION para buscar.");
            return;
        }

        try {
            File archivo = obtenerArchivoInventarios();
            try (Workbook libro = cargarLibro(archivo)) {
                Sheet hoja = obtenerHojaInventarios(libro);
                asegurarEncabezados(hoja);

                int filaIndex = -1;
                if (!codigo.isEmpty()) {
                    filaIndex = buscarFilaPorCodigo(hoja, codigo);
                }
                if (filaIndex < 0 && !descripcion.isEmpty()) {
                    filaIndex = buscarFilaPorDescripcion(hoja, descripcion);
                }
                if (filaIndex < 0) {
                    filaInventarioActual = -1;
                    restablecerIndicadorEstado();
                    JOptionPane.showMessageDialog(this, "No se encontro un inventario con los datos capturados.");
                    return;
                }

                Row fila = hoja.getRow(filaIndex);
                if (fila == null) {
                    filaInventarioActual = -1;
                    restablecerIndicadorEstado();
                    JOptionPane.showMessageDialog(this, "El registro encontrado esta vacio.");
                    return;
                }

                cargarFilaEnFormulario(fila);
                filaInventarioActual = filaIndex;

                String codigoEncontrado = leerCelda(fila, 0);
                String estado = normalizarEstado(leerCelda(fila, 5));
                actualizarIndicadorEstado(estado);
                String estadoTexto = "1".equals(estado) ? "ACTIVO (1)" : "INACTIVO (0)";
                JOptionPane.showMessageDialog(this, "Inventario encontrado.\nCODIGO: " + codigoEncontrado + "\nEstado: " + estadoTexto);
            }
        } catch (IOException ex) {
            restablecerIndicadorEstado();
            mostrarError("No se pudo buscar el inventario.", ex);
        }
    }//buscarInventario

    private boolean validarCamposBase() {
        if (jTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "CODIGO es obligatorio.");
            return false;
        }
        if (jTextField2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DESCRIPCION es obligatoria.");
            return false;
        }
        return true;
    }//validarCamposBase

    private int resolverFilaInventario(Sheet hoja) {
        if (filaInventarioActual > 0 && filaInventarioActual <= hoja.getLastRowNum()) {
            Row fila = hoja.getRow(filaInventarioActual);
            if (fila != null) {
                String codigoCapturado = jTextField1.getText().trim();
                String codigoFila = leerCelda(fila, 0);
                if (codigoCapturado.isEmpty() || codigoCapturado.equalsIgnoreCase(codigoFila)) {
                    return filaInventarioActual;
                }
            }
        }

        String codigo = jTextField1.getText().trim();
        if (!codigo.isEmpty()) {
            int filaPorCodigo = buscarFilaPorCodigo(hoja, codigo);
            if (filaPorCodigo >= 0) {
                return filaPorCodigo;
            }
        }

        String descripcion = jTextField2.getText().trim();
        if (!descripcion.isEmpty()) {
            int filaPorDesc = buscarFilaPorDescripcion(hoja, descripcion);
            if (filaPorDesc >= 0) {
                return filaPorDesc;
            }
        }

        return -1;
    }//resolverFilaInventario

    private void guardarDatosEnFila(Row fila) {
        escribirCelda(fila, 0, jTextField1.getText().trim());
        escribirCelda(fila, 1, jTextField2.getText().trim());
        escribirCelda(fila, 2, jTextField3.getText().trim());
        escribirCelda(fila, 3, jTextField5.getText().trim());
        escribirCelda(fila, 4, jTextField6.getText().trim());
    }//guardarDatosEnFila

    private void cargarFilaEnFormulario(Row fila) {
        jTextField1.setText(leerCelda(fila, 0));
        jTextField2.setText(leerCelda(fila, 1));
        jTextField3.setText(leerCelda(fila, 2));
        jTextField5.setText(leerCelda(fila, 3));
        jTextField6.setText(leerCelda(fila, 4));
    }//cargarFilaEnFormulario

    private void limpiarFormulario(boolean conservarCodigo) {
        if (!conservarCodigo) {
            jTextField1.setText("");
        }
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        filaInventarioActual = -1;
        restablecerIndicadorEstado();
    }//limpiarFormulario

    private int buscarFilaPorId(Sheet hoja, String id) {
        for (int fila = 1; fila <= hoja.getLastRowNum(); fila++) {
            Row row = hoja.getRow(fila);
            if (row == null) {
                continue;
            }
            if (id.equalsIgnoreCase(leerCelda(row, 0))) {
                return fila;
            }
        }
        return -1;
    }//buscarFilaPorId

    private int buscarFilaPorCodigo(Sheet hoja, String codigo) {
        for (int fila = 1; fila <= hoja.getLastRowNum(); fila++) {
            Row row = hoja.getRow(fila);
            if (row == null) {
                continue;
            }
            if (codigo.equalsIgnoreCase(leerCelda(row, 0))) {
                return fila;
            }
        }
        return -1;
    }//buscarFilaPorCodigo

    private int buscarFilaPorDescripcion(Sheet hoja, String descripcion) {
        for (int fila = 1; fila <= hoja.getLastRowNum(); fila++) {
            Row row = hoja.getRow(fila);
            if (row == null) {
                continue;
            }
            if (descripcion.equalsIgnoreCase(leerCelda(row, 1))) {
                return fila;
            }
        }
        return -1;
    }//buscarFilaPorDescripcion

    private int primeraFilaDisponible(Sheet hoja) {
        for (int fila = 1; fila <= hoja.getLastRowNum(); fila++) {
            Row row = hoja.getRow(fila);
            if (row == null || leerCelda(row, 0).isEmpty()) {
                return fila;
            }
        }
        return hoja.getLastRowNum() + 1;
    }//primeraFilaDisponible

    private String generarIdInventario(Sheet hoja, String codigo) {
        String base = codigo == null ? "" : codigo.replaceAll("[^A-Za-z0-9]", "").toLowerCase();
        if (base.isEmpty()) {
            base = "inv";
        }
        if (base.length() > 4) {
            base = base.substring(0, 4);
        }
        while (base.length() < 4) {
            base = base + "x";
        }
        for (int i = 1; i <= 999; i++) {
            String sufijo = i <= 99 ? String.format("%02d", i) : String.valueOf(i);
            String candidato = base + sufijo;
            if (buscarFilaPorId(hoja, candidato) < 0) {
                return candidato;
            }
        }
        return base + System.currentTimeMillis();
    }//generarIdInventario

    private boolean asegurarEncabezados(Sheet hoja) {
        boolean huboCambios = false;
        Row filaEncabezado = hoja.getRow(0);
        if (filaEncabezado == null) {
            filaEncabezado = hoja.createRow(0);
            huboCambios = true;
        }
        for (int columna = 0; columna < ENCABEZADOS.length; columna++) {
            Cell celda = filaEncabezado.getCell(columna, Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);
            String valorEsperado = ENCABEZADOS[columna];
            if (celda == null) {
                celda = filaEncabezado.createCell(columna);
                celda.setCellValue(valorEsperado);
                huboCambios = true;
                continue;
            }
            String valorActual = DATA_FORMATTER.formatCellValue(celda).trim();
            if (!valorEsperado.equalsIgnoreCase(valorActual)) {
                celda.setCellValue(valorEsperado);
                huboCambios = true;
            }
        }
        return huboCambios;
    }//asegurarEncabezados

    private Sheet obtenerHojaInventarios(Workbook libro) {
        if (libro.getNumberOfSheets() == 0) {
            return libro.createSheet("INVENTARIOS");
        }
        return libro.getSheetAt(0);
    }//obtenerHojaInventarios

    private Workbook cargarLibro(File archivo) throws IOException {
        if (!archivo.exists()) {
            Workbook libroNuevo = new XSSFWorkbook();
            Sheet hojaNueva = libroNuevo.createSheet("INVENTARIOS");
            asegurarEncabezados(hojaNueva);
            guardarLibro(libroNuevo, archivo);
            return libroNuevo;
        }
        try (FileInputStream fis = new FileInputStream(archivo)) {
            return new XSSFWorkbook(fis);
        }
    }//cargarLibro

    private void guardarLibro(Workbook libro, File archivo) throws IOException {
        try (FileOutputStream fos = new FileOutputStream(archivo)) {
            libro.write(fos);
        }
    }//guardarLibro

    private File obtenerArchivoInventarios() {
        File archivoAbsoluto = new File(INVENTARIOS_FILE_ABSOLUTE);
        if (archivoAbsoluto.exists()) {
            return archivoAbsoluto;
        }
        File archivoRelativo = new File(INVENTARIOS_FILE_RELATIVE);
        if (archivoRelativo.exists()) {
            return archivoRelativo;
        }
        File parent = archivoAbsoluto.getParentFile();
        if (parent != null && !parent.exists()) {
            parent.mkdirs();
        }
        return archivoAbsoluto;
    }//obtenerArchivoInventarios

    private String leerCelda(Row fila, int columna) {
        if (fila == null) {
            return "";
        }
        Cell celda = fila.getCell(columna, Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);
        if (celda == null) {
            return "";
        }
        return DATA_FORMATTER.formatCellValue(celda).trim();
    }//leerCelda

    private void escribirCelda(Row fila, int columna, String valor) {
        Cell celda = fila.getCell(columna, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK);
        celda.setCellValue(valor == null ? "" : valor.trim());
    }//escribirCelda

    private String normalizarEstado(String valor) {
        String limpio = valor == null ? "" : valor.trim();
        if (limpio.isEmpty()) {
            return "1";
        }
        if ("1".equals(limpio)) {
            return "1";
        }
        if ("0".equals(limpio)) {
            return "0";
        }
        try {
            return Double.parseDouble(limpio) > 0 ? "1" : "0";
        } catch (NumberFormatException ex) {
            if ("ACTIVO".equalsIgnoreCase(limpio)
                    || "SI".equalsIgnoreCase(limpio)
                    || "TRUE".equalsIgnoreCase(limpio)) {
                return "1";
            }
            return "0";
        }
    }//normalizarEstado

    private void actualizarIndicadorEstado(String estado) {
        String estadoNormalizado = normalizarEstado(estado);
        if ("1".equals(estadoNormalizado)) {
            jButton3.setText("DESACTIVAR (ACTIVO)");
            jButton3.setForeground(new java.awt.Color(0, 120, 0));
            jButton3.setToolTipText("Estado actual: ACTIVO (1)");
            return;
        }
        jButton3.setText("ACTIVAR (INACTIVO)");
        jButton3.setForeground(new java.awt.Color(180, 0, 0));
        jButton3.setToolTipText("Estado actual: INACTIVO (0)");
    }//actualizarIndicadorEstado

    private void restablecerIndicadorEstado() {
        jButton3.setText("ELIMINAR");
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setToolTipText("Estado actual: sin seleccionar");
    }//restablecerIndicadorEstado

    private void mostrarError(String mensajeUsuario, Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, mensajeUsuario, ex);
        JOptionPane.showMessageDialog(this, mensajeUsuario + "\nDetalle tecnico: " + ex.getMessage());
    }//mostrarError
}

