/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ocxrst;

import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.itextpdf.layout.properties.VerticalAlignment;
import java.io.File;
import java.io.FileInputStream;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author Maria Luisa Martinez
 */
public class ORDENCOMPRA extends javax.swing.JFrame {

    private static final String RUTA_INVENTARIOS = "C:\\OCXRST\\OrdendeComprasRST\\src\\main\\java\\com\\mycompany\\ocxrst\\BASES\\INVENTARIOS.xlsx";
    private final DataFormatter dataFormatter = new DataFormatter();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ORDENCOMPRA.class.getName());

    public ORDENCOMPRA() {
        initComponents();
        IconoVentanaUtil.aplicar(this);
        configurarTablaProductos();
        cargarCFDI();
        cargarUsuario();
        actualizarTotales();
    setLocationRelativeTo(null); 
        setLocationRelativeTo(null); 
    
    jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusLost(java.awt.event.FocusEvent e) {
        buscarProveedor(jTextField1.getText());
    }
});

    jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusLost(java.awt.event.FocusEvent e) {
        procesarCodigoProducto();
    }
});
    
  jComboBox1.addActionListener(e -> {
    String seleccionado = jComboBox1.getSelectedItem().toString();
    buscarArea(seleccionado);
});

    jButton7.addActionListener(e -> eliminarFilaSeleccionada());

    // Auto-llenar jTextField4 con AVANTE + AñoMesDía (editable)
    java.time.LocalDate hoy = java.time.LocalDate.now();
    String cotizacion = String.format("AVANTE%04d%02d%02d",
            hoy.getYear(), hoy.getMonthValue(), hoy.getDayOfMonth());
    jTextField4.setText(cotizacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ORDEN DE COMPRA");

        jButton6.setBackground(new java.awt.Color(0, 0, 153));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("< ATRAS");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jLabel2.setText("PROVEEDOR:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("FECHA:");

        jLabel4.setText("AREA:");

        jLabel6.setText("ID_PROVEEDOR:");

        jLabel7.setText("SOLICITANTE:");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel9.setText("NO.");

        jLabel10.setText("NUMERO");

        jLabel11.setText("COTIZACIÓN:");

        jLabel13.setText("PROYECTO:");

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("DIRECCIÓN:");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel15.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel15ComponentShown(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FO-SG-04-00");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Unidad de Medida", "Cantidad", "Precio", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel16.setText("PRODUCTO:");

        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jButton7.setText("Eliminar");

        jLabel17.setText("USO CFDI:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(this::jComboBox3ActionPerformed);

        jLabel18.setText("PAGO:");

        jLabel19.setText("METODO DE PAGO:");

        jLabel20.setText("SUB TOTAL:");

        jLabel21.setText("IVA 16%: ");

        jLabel22.setText("TOTAL:");

        jButton1.setText("CREAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("jLabel23");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("jLabel24");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("jLabel25");

        jLabel29.setText("RFC:");

        jLabel31.setText("CONTACTO:");

        jLabel12.setText("TIEMPO DE ENTREGA:");

        jLabel34.setText("FORMA DE PAGO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel10)
                                            .addGap(190, 190, 190)
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(38, 38, 38)
                                            .addComponent(jButton7))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel31)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel13)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel18)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(23, 23, 23)
                                            .addComponent(jLabel29)
                                            .addGap(17, 17, 17)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel34))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(322, 322, 322))))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel3)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        PRINCIPAL ventana = new PRINCIPAL();
        ventana.setVisible(true); // 👉 abre la nueva ventana

        this.dispose(); // 👉 cierra el login        
    }//GEN-LAST:event_jButton6ActionPerformed

   

    public void buscarProveedor(String idBuscado) {
    try {
        FileInputStream file = new FileInputStream("C:\\OCXRST\\OrdendeComprasRST\\src\\main\\java\\com\\mycompany\\ocxrst\\BASES\\proveedores.xlsx");
        Workbook workbook = new XSSFWorkbook(file);
        Sheet sheet = workbook.getSheetAt(0);

        for (Row row : sheet) {

            if (row.getRowNum() == 0) continue;

            org.apache.poi.ss.usermodel.Cell celdaId = row.getCell(0);

            if (celdaId != null) {

                String valorCelda = celdaId.toString();

                if (valorCelda.equalsIgnoreCase(idBuscado)) {
                    String nombre = row.getCell(1).toString();
                    jLabel8.setText(nombre);
                    String direccion = row.getCell(5).toString();
                    jLabel15.setText("<html>" + direccion + "</html>");
                    String formadepago = row.getCell(7).toString();
                    jLabel27.setText("<html>" + formadepago+ "</html>");
                    String metododepago = row.getCell(8).toString();
                    jLabel28.setText("<html>" + metododepago + "</html>");
                    workbook.close();
                    String RFC = row.getCell(2).toString();
                    jLabel30.setText("<html>" + RFC + "</html>");
                    workbook.close();
                    String contacto = row.getCell(6).toString();
                    jLabel32.setText("<html>" + contacto + "</html>");
                    workbook.close();
                    String tiempoentrega = row.getCell(9).toString();
                    jLabel33.setText("<html>" + tiempoentrega + "</html>");
                    workbook.close();
                    String formapago = row.getCell(10).toString();
                    jLabel35.setText("<html>" + formapago + "</html>");
                    workbook.close();
                    return;
                }
            }
        }

        jLabel8.setText("Proveedor no encontrado");

        workbook.close();

    } catch (Exception e) {
        e.printStackTrace();
        jLabel8.setText("Error");
    }
}

    private void configurarTablaProductos() {
    jTable1.setModel(new DefaultTableModel(
        new Object[][] {},
        new String[] {"Código", "Descripción", "Unidad de Medida", "Cantidad", "Precio", "Importe"}
    ) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return switch (columnIndex) {
                case 0, 1, 2 -> String.class;
                case 3 -> Integer.class;
                case 4, 5 -> Double.class;
                default -> Object.class;
            };
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return columnIndex == 3;
        }

        @Override
        public void setValueAt(Object aValue, int row, int column) {
            if (column == 3) {
                int cantidad = parseCantidad(aValue);
                super.setValueAt(cantidad, row, 3);

                Object precioObj = getValueAt(row, 4);
                double precio = parseNumero(precioObj);
                super.setValueAt(precio * cantidad, row, 5);
                ORDENCOMPRA.this.actualizarTotales();
                return;
            }

            super.setValueAt(aValue, row, column);
        }
    });
}

    private int parseCantidad(Object valor) {
    if (valor == null) {
        return 1;
    }

    if (valor instanceof Number numero) {
        return Math.max(1, numero.intValue());
    }

    try {
        return Math.max(1, Integer.parseInt(valor.toString().trim()));
    } catch (NumberFormatException e) {
        return 1;
    }
}

    private double parseNumero(Object valor) {
    if (valor == null) {
        return 0;
    }

    if (valor instanceof Number numero) {
        return numero.doubleValue();
    }

    try {
        return Double.parseDouble(valor.toString().trim().replace(",", ""));
    } catch (NumberFormatException e) {
        return 0;
    }
}

    private void procesarCodigoProducto() {
    String codigoBuscado = jTextField3.getText().trim();

    if (codigoBuscado.isEmpty()) {
        return;
    }

    if (buscarProducto(codigoBuscado)) {
        jTextField3.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Producto no encontrado en INVENTARIOS.", "Inventarios", JOptionPane.WARNING_MESSAGE);
        jTextField3.requestFocus();
        jTextField3.selectAll();
    }
}
    
    public boolean buscarProducto(String codigoBuscado) {
    try (FileInputStream file = new FileInputStream(RUTA_INVENTARIOS);
         Workbook workbook = new XSSFWorkbook(file)) {

        Sheet sheet = workbook.getSheetAt(0);

        for (Row row : sheet) {
            if (row.getRowNum() == 0) {
                continue;
            }

            String codigo = obtenerTextoCelda(row.getCell(0));

            if (codigo.equalsIgnoreCase(codigoBuscado.trim())) {
                String descripcion = obtenerTextoCelda(row.getCell(1));
                String unidad = obtenerTextoCelda(row.getCell(2));
                double precio = obtenerNumeroCelda(row.getCell(3));

                agregarATabla(codigo, descripcion, unidad, precio);
                return true;
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "No se pudo leer el archivo INVENTARIOS.xlsx", "Error", JOptionPane.ERROR_MESSAGE);
    }

    return false;
}

    private String obtenerTextoCelda(org.apache.poi.ss.usermodel.Cell celda) {
    if (celda == null) {
        return "";
    }

    return dataFormatter.formatCellValue(celda).trim();
}

    private double obtenerNumeroCelda(org.apache.poi.ss.usermodel.Cell celda) {
    if (celda == null) {
        return 0;
    }

    if (celda.getCellType() == CellType.NUMERIC) {
        return celda.getNumericCellValue();
    }

    String valor = dataFormatter.formatCellValue(celda).trim().replace(",", "");
    return valor.isEmpty() ? 0 : Double.parseDouble(valor);
}

    public void agregarATabla(String codigo, String descripcion, String unidad, double precio) {

    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

    int filaExistente = buscarFilaPorCodigo(modelo, codigo);
    if (filaExistente >= 0) {
        JOptionPane.showMessageDialog(this, "El codigo ya existe en la tabla.", "Producto duplicado", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    Object[] fila = new Object[6];

    fila[0] = codigo;
    fila[1] = descripcion;
    fila[2] = unidad;
    fila[3] = 1; // cantidad
    fila[4] = precio;
    fila[5] = precio * 1;

    modelo.addRow(fila);
    modelo.fireTableDataChanged();
    actualizarTotales();
}

    private void eliminarFilaSeleccionada() {
    int filaSeleccionada = jTable1.getSelectedRow();

    if (filaSeleccionada < 0) {
        JOptionPane.showMessageDialog(this, "Selecciona un producto para eliminar.", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.removeRow(filaSeleccionada);
    actualizarTotales();
}

    private void actualizarTotales() {
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    double subtotal = 0;

    for (int i = 0; i < modelo.getRowCount(); i++) {
        int cantidad = parseCantidad(modelo.getValueAt(i, 3));
        double precio = parseNumero(modelo.getValueAt(i, 4));
        double importe = cantidad * precio;

        modelo.setValueAt(importe, i, 5);
        subtotal += importe;
    }

    double iva = subtotal * 0.16;
    double total = subtotal + iva;

    jLabel23.setText(String.format("$ %.2f", subtotal));
    jLabel24.setText(String.format("$ %.2f", iva));
    jLabel25.setText(String.format("$ %.2f", total));
}

    private int buscarFilaPorCodigo(DefaultTableModel modelo, String codigo) {
    String codigoNormalizado = codigo == null ? "" : codigo.trim();

    for (int i = 0; i < modelo.getRowCount(); i++) {
        Object codigoFila = modelo.getValueAt(i, 0);
        if (codigoFila != null && codigoFila.toString().trim().equalsIgnoreCase(codigoNormalizado)) {
            return i;
        }
    }

    return -1;
}
    
    public void cargarCFDI() {
    try {
        FileInputStream file = new FileInputStream(
            "C:\\OCXRST\\OrdendeComprasRST\\src\\main\\java\\com\\mycompany\\ocxrst\\BASES\\CFDI.xlsx"
        );

        Workbook workbook = new XSSFWorkbook(file);
        Sheet sheet = workbook.getSheetAt(0);

        jComboBox3.removeAllItems();

        boolean primeraFila = true;

        for (Row row : sheet) {

            if (primeraFila) {
                primeraFila = false; // 👉 saltar encabezado
                continue;
            }

            org.apache.poi.ss.usermodel.Cell cell = row.getCell(0); // columna A

            if (cell != null) {
                jComboBox3.addItem(cell.toString());
            }
        }

        workbook.close();
        file.close();

    } catch (Exception e) {
        e.printStackTrace();
    }
}
     
      public void cargarUsuario() {
    try {
        FileInputStream User = new FileInputStream(
            "C:\\OCXRST\\OrdendeComprasRST\\src\\main\\java\\com\\mycompany\\ocxrst\\BASES\\USUARIOS.xlsx"
        );

        Workbook workbook = new XSSFWorkbook(User);
        Sheet sheet = workbook.getSheetAt(0);

        jComboBox1.removeAllItems();

        boolean primeraFila = true;

        for (Row row : sheet) {

            if (primeraFila) {
                primeraFila = false; // 👉 saltar encabezado
                continue;
            }

            org.apache.poi.ss.usermodel.Cell cell = row.getCell(2); // columna A

            if (cell != null) {
                jComboBox1.addItem(cell.toString());
            }
        }

        workbook.close();
        User.close();

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
      public void buscarArea(String idBuscado) {
    try {
        FileInputStream file = new FileInputStream("C:\\OCXRST\\OrdendeComprasRST\\src\\main\\java\\com\\mycompany\\ocxrst\\BASES\\USUARIOS.xlsx");
        Workbook workbook = new XSSFWorkbook(file);
        Sheet sheet = workbook.getSheetAt(0);
        for (Row row : sheet) {
            if (row.getRowNum() == 0) continue;
            org.apache.poi.ss.usermodel.Cell celdaId = row.getCell(2);
            if (celdaId != null) {
                String valorCelda = celdaId.toString();
                if (valorCelda.equalsIgnoreCase(idBuscado)) {
                    String area= row.getCell(3).toString();
                    jLabel26.setText(area);
                   
                    workbook.close();
                    return;
                }
            }
        }
        jLabel26.setText("Proveedor no encontrado");
        workbook.close();
    } catch (Exception e) {
        e.printStackTrace();
        jLabel26.setText("Error");
    }
}
      
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        procesarCodigoProducto();
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        generarPDF();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel15ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel15ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15ComponentShown

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    // ─────────────────────────────────────────────────────────────────────────
    //  PDF GENERATION
    // ─────────────────────────────────────────────────────────────────────────
    private static final String LOGO_PDF_PATH =
        "C:\\OCXRST\\OrdendeComprasRST\\src\\main\\java\\com\\mycompany\\ocxrst\\IMAGENES\\Logo PDF.png";

    private void generarPDF() {
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setDialogTitle("Guardar Orden de Compra");
        fc.setSelectedFile(new File(System.getProperty("user.home") + "\\Desktop\\OrdenCompra_" + jTextField4.getText() + ".pdf"));
        fc.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("PDF (*.pdf)", "pdf"));
        if (fc.showSaveDialog(this) != javax.swing.JFileChooser.APPROVE_OPTION) return;

        String ruta = fc.getSelectedFile().getAbsolutePath();
        if (!ruta.toLowerCase().endsWith(".pdf")) ruta += ".pdf";

        try {
            PdfWriter  writer = new PdfWriter(ruta);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document   doc    = new Document(pdfDoc, PageSize.LETTER);
            doc.setMargins(36, 36, 36, 36);

            PdfFont bold  = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);
            PdfFont plain = PdfFontFactory.createFont(StandardFonts.HELVETICA);
            DeviceRgb azul      = new DeviceRgb(0, 0, 153);
            DeviceRgb azulClaro = new DeviceRgb(220, 230, 241);
            DeviceRgb blanco    = new DeviceRgb(255, 255, 255);

            // ── ENCABEZADO ────────────────────────────────────────────────────
            Table header = new Table(UnitValue.createPercentArray(new float[]{25, 50, 25}))
                    .useAllAvailableWidth().setMarginBottom(6);

            Image logo = new Image(ImageDataFactory.create(LOGO_PDF_PATH)).scaleToFit(130, 55);
            header.addCell(new Cell().add(logo)
                    .setBorder(Border.NO_BORDER).setPadding(4)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE));

            header.addCell(new Cell()
                    .add(new Paragraph("ORDEN DE COMPRA")
                            .setFont(bold).setFontSize(18).setFontColor(azul)
                            .setTextAlignment(TextAlignment.CENTER))
                    .add(new Paragraph("RED SINERGIA DE TELECOMUNICACIONES, S.A. DE C.V.\nAv. Ocote #10 Arboledas Guadalupe, C.P. 72260. RST140517D48\nTELS.: +52 (01 2222) 278842, (01 55) 7823 1585")
                            .setFont(plain).setFontSize(7).setFontColor(azul)
                            .setTextAlignment(TextAlignment.CENTER))
                    .setBorder(Border.NO_BORDER).setPadding(4)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE));

            header.addCell(new Cell()
                    .add(new Paragraph("FO-SG-04-00")
                            .setFont(bold).setFontSize(8)
                            .setTextAlignment(TextAlignment.RIGHT))
                    .add(new Paragraph("NO.  " + jLabel10.getText())
                            .setFont(bold).setFontSize(9).setFontColor(azul)
                            .setTextAlignment(TextAlignment.RIGHT))
                    .add(new Paragraph("Cotización: " + jTextField4.getText())
                            .setFont(plain).setFontSize(9)
                            .setTextAlignment(TextAlignment.RIGHT))
                    .setBorder(Border.NO_BORDER).setPadding(4)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE));
            doc.add(header);

            // Línea separadora azul
            doc.add(new Paragraph("").setBorderBottom(new SolidBorder(azul, 2)).setMarginBottom(6));

            // ── INFORMACIÓN GENERAL ───────────────────────────────────────────
            String fecha = "";
            if (jDateChooser2.getDate() != null) {
                fecha = new SimpleDateFormat("dd/MM/yyyy").format(jDateChooser2.getDate());
            }
            Object cfdi = jComboBox3.getSelectedItem();

            Table infoGen = new Table(UnitValue.createPercentArray(new float[]{2, 4, 2, 4}))
                    .useAllAvailableWidth().setMarginBottom(4);
            addFilaPDF(infoGen, bold, plain, azul,
                    "FECHA:", fecha,
                    "PROYECTO:", jTextField2.getText());
            doc.add(infoGen);

            // ── DATOS DEL PROVEEDOR ───────────────────────────────────────────
            doc.add(seccionTitulo("DATOS DEL PROVEEDOR", bold, azul));

            Table provTbl = new Table(UnitValue.createPercentArray(new float[]{2, 4, 2, 4}))
                    .useAllAvailableWidth().setMarginBottom(4);
            addFilaPDF(provTbl, bold, plain, azul,
                    "ID PROVEEDOR:", jTextField1.getText(),
                    "PROVEEDOR:",    jLabel8.getText());
            addFilaPDF(provTbl, bold, plain, azul,
                    "RFC:",          stripHtmlPDF(jLabel30.getText()),
                    "DIRECCIÓN:",    stripHtmlPDF(jLabel15.getText()));
            addFilaPDF(provTbl, bold, plain, azul,
                    "CONTACTO:",     stripHtmlPDF(jLabel32.getText()),
                    "", "");
            doc.add(provTbl);

            // ── CONDICIONES COMERCIALES ───────────────────────────────────────
            doc.add(seccionTitulo("CONDICIONES COMERCIALES", bold, azul));

            Table condTbl = new Table(UnitValue.createPercentArray(new float[]{2, 4, 2, 4}))
                    .useAllAvailableWidth().setMarginBottom(4);
            addFilaPDF(condTbl, bold, plain, azul,
                    "PAGO:", stripHtmlPDF(jLabel27.getText()),
                    "TIEMPO DE ENTREGA:", stripHtmlPDF(jLabel33.getText()));
            doc.add(condTbl);

            // ── DATOS DE LA SOLICITUD ─────────────────────────────────────────
            doc.add(seccionTitulo("DATOS DE LA SOLICITUD", bold, azul));

            Object solicitante = jComboBox1.getSelectedItem();
            Table solTbl = new Table(UnitValue.createPercentArray(new float[]{2, 4, 2, 4}))
                    .useAllAvailableWidth().setMarginBottom(6);
            addFilaPDF(solTbl, bold, plain, azul,
                    "SOLICITANTE:", solicitante != null ? solicitante.toString() : "",
                    "ÁREA:",        jLabel26.getText());
            doc.add(solTbl);

            // ── TABLA DE PRODUCTOS ────────────────────────────────────────────
            doc.add(seccionTitulo("PRODUCTOS / SERVICIOS", bold, azul));

            Table prodTbl = new Table(UnitValue.createPercentArray(new float[]{1.5f, 4f, 2f, 1f, 1.5f, 1.5f}))
                    .useAllAvailableWidth().setMarginBottom(4);

            String[] colHeaders = {"CÓDIGO", "DESCRIPCIÓN", "UNIDAD DE MEDIDA", "CANT.", "PRECIO UNIT.", "IMPORTE"};
            TextAlignment[] colAligns = {
                TextAlignment.CENTER, TextAlignment.LEFT, TextAlignment.CENTER,
                TextAlignment.CENTER, TextAlignment.RIGHT, TextAlignment.RIGHT
            };
            for (int c = 0; c < colHeaders.length; c++) {
                prodTbl.addHeaderCell(new Cell()
                        .add(new Paragraph(colHeaders[c]).setFont(bold).setFontSize(8)
                                .setFontColor(ColorConstants.WHITE))
                        .setBackgroundColor(azul)
                        .setTextAlignment(colAligns[c])
                        .setPadding(4));
            }

            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            boolean filaAlterna = false;
            for (int i = 0; i < modelo.getRowCount(); i++) {
                Object cod = modelo.getValueAt(i, 0);
                if (cod == null || cod.toString().trim().isEmpty()) continue;
                DeviceRgb bgFila = filaAlterna ? azulClaro : blanco;
                prodTbl.addCell(celdaTablaPDF(cod,                    plain, TextAlignment.CENTER, bgFila));
                prodTbl.addCell(celdaTablaPDF(modelo.getValueAt(i, 1), plain, TextAlignment.LEFT,   bgFila));
                prodTbl.addCell(celdaTablaPDF(modelo.getValueAt(i, 2), plain, TextAlignment.CENTER, bgFila));
                prodTbl.addCell(celdaTablaPDF(modelo.getValueAt(i, 3), plain, TextAlignment.CENTER, bgFila));
                prodTbl.addCell(celdaMonedaPDF(modelo.getValueAt(i, 4), plain, bgFila));
                prodTbl.addCell(celdaMonedaPDF(modelo.getValueAt(i, 5), plain, bgFila));
                filaAlterna = !filaAlterna;
            }
            doc.add(prodTbl);

            // ── TOTALES ───────────────────────────────────────────────────────
            Table totTbl = new Table(UnitValue.createPercentArray(new float[]{6, 2, 2}))
                    .useAllAvailableWidth().setMarginTop(2);
            totTbl.addCell(new Cell(3, 1).setBorder(Border.NO_BORDER));  // espacio izq.

            // Subtotal
            totTbl.addCell(new Cell()
                    .add(new Paragraph("SUB TOTAL:").setFont(bold).setFontSize(10))
                    .setTextAlignment(TextAlignment.RIGHT).setBackgroundColor(azulClaro)
                    .setBorder(new SolidBorder(azul, 1)).setPadding(4));
            totTbl.addCell(new Cell()
                    .add(new Paragraph(jLabel23.getText()).setFont(bold).setFontSize(10))
                    .setTextAlignment(TextAlignment.RIGHT).setBackgroundColor(azulClaro)
                    .setBorder(new SolidBorder(azul, 1)).setPadding(4));

            // IVA
            totTbl.addCell(new Cell()
                    .add(new Paragraph("IVA 16%:").setFont(bold).setFontSize(10))
                    .setTextAlignment(TextAlignment.RIGHT).setBackgroundColor(azulClaro)
                    .setBorderLeft(new SolidBorder(azul, 1))
                    .setBorderRight(new SolidBorder(azul, 1))
                    .setBorderTop(Border.NO_BORDER)
                    .setBorderBottom(new SolidBorder(azul, 1)).setPadding(4));
            totTbl.addCell(new Cell()
                    .add(new Paragraph(jLabel24.getText()).setFont(bold).setFontSize(10))
                    .setTextAlignment(TextAlignment.RIGHT).setBackgroundColor(azulClaro)
                    .setBorderLeft(Border.NO_BORDER)
                    .setBorderRight(new SolidBorder(azul, 1))
                    .setBorderTop(Border.NO_BORDER)
                    .setBorderBottom(new SolidBorder(azul, 1)).setPadding(4));

            // Total
            totTbl.addCell(new Cell()
                    .add(new Paragraph("TOTAL:").setFont(bold).setFontSize(11)
                            .setFontColor(ColorConstants.WHITE))
                    .setTextAlignment(TextAlignment.RIGHT).setBackgroundColor(azul)
                    .setBorder(new SolidBorder(azul, 1)).setPadding(5));
            totTbl.addCell(new Cell()
                    .add(new Paragraph(jLabel25.getText()).setFont(bold).setFontSize(11)
                            .setFontColor(ColorConstants.WHITE))
                    .setTextAlignment(TextAlignment.RIGHT).setBackgroundColor(azul)
                    .setBorder(new SolidBorder(azul, 1)).setPadding(5));
            doc.add(totTbl);

            // Línea separadora azul (debajo de totales)
            doc.add(new Paragraph("").setBorderBottom(new SolidBorder(azul, 2)).setMarginBottom(6));

            // ── INFORMACIÓN DE FACTURA ────────────────────────────────────────
            doc.add(new Paragraph("La generación de la factura debe incluir la siguiente información:")
                    .setFont(bold).setFontSize(9).setFontColor(azul).setMarginBottom(4));
            Table factTbl = new Table(UnitValue.createPercentArray(new float[]{2, 4}))
                    .useAllAvailableWidth().setMarginBottom(10);
            factTbl.addCell(new Cell()
                    .add(new Paragraph("USO CFDI:").setFont(bold).setFontSize(9).setFontColor(azul))
                    .setBorder(Border.NO_BORDER).setPadding(3));
            factTbl.addCell(new Cell()
                    .add(new Paragraph(cfdi != null ? cfdi.toString() : "").setFont(plain).setFontSize(9))
                    .setBorder(Border.NO_BORDER).setPadding(3));
            factTbl.addCell(new Cell()
                    .add(new Paragraph("MÉTODO DE PAGO:").setFont(bold).setFontSize(9).setFontColor(azul))
                    .setBorder(Border.NO_BORDER).setPadding(3));
            factTbl.addCell(new Cell()
                    .add(new Paragraph(stripHtmlPDF(jLabel28.getText())).setFont(plain).setFontSize(9))
                    .setBorder(Border.NO_BORDER).setPadding(3));
            doc.add(factTbl);

            // ── FIRMAS ────────────────────────────────────────────────────────
            doc.add(new Paragraph(" ").setMarginTop(30));
            Table firmasTbl = new Table(UnitValue.createPercentArray(new float[]{1, 1, 1}))
                    .useAllAvailableWidth().setMarginTop(10);
            for (String rol : new String[]{"ELABORÓ", "AUTORIZÓ", "RECIBIÓ"}) {
                firmasTbl.addCell(new Cell()
                        .add(new Paragraph("\n\n\n___________________________\n" + rol)
                                .setFont(bold).setFontSize(9)
                                .setTextAlignment(TextAlignment.CENTER))
                        .setBorder(Border.NO_BORDER));
            }
            doc.add(firmasTbl);

            doc.close();

            JOptionPane.showMessageDialog(this, "PDF generado exitosamente.", "Listo", JOptionPane.INFORMATION_MESSAGE);
            try { java.awt.Desktop.getDesktop().open(new File(ruta)); } catch (Exception ignored) {}

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error generando PDF", ex);
            JOptionPane.showMessageDialog(this, "Error al generar el PDF:\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** Fila de 2 pares etiqueta-valor para tablas de información */
    private void addFilaPDF(Table tbl, PdfFont bold, PdfFont plain, DeviceRgb azul,
                            String lbl1, String val1, String lbl2, String val2) {
        tbl.addCell(new Cell()
                .add(new Paragraph(lbl1).setFont(bold).setFontSize(9).setFontColor(azul))
                .setBorder(Border.NO_BORDER).setPadding(3));
        tbl.addCell(new Cell()
                .add(new Paragraph(val1 != null ? val1 : "").setFont(plain).setFontSize(9))
                .setBorder(Border.NO_BORDER).setPadding(3)
                .setVerticalAlignment(VerticalAlignment.TOP));
        tbl.addCell(new Cell()
                .add(new Paragraph(lbl2).setFont(bold).setFontSize(9).setFontColor(azul))
                .setBorder(Border.NO_BORDER).setPadding(3));
        tbl.addCell(new Cell()
                .add(new Paragraph(val2 != null ? val2 : "").setFont(plain).setFontSize(9))
                .setBorder(Border.NO_BORDER).setPadding(3)
                .setVerticalAlignment(VerticalAlignment.TOP));
    }

    /** Celda de encabezado de sección (fondo azul, texto blanco) */
    private Table seccionTitulo(String titulo, PdfFont bold, DeviceRgb azul) {
        Table t = new Table(UnitValue.createPercentArray(new float[]{1})).useAllAvailableWidth();
        t.addCell(new Cell()
                .add(new Paragraph(titulo).setFont(bold).setFontSize(9)
                        .setFontColor(ColorConstants.WHITE))
                .setBackgroundColor(azul).setPadding(3).setBorder(Border.NO_BORDER));
        return t;
    }

    private Cell celdaTablaPDF(Object val, PdfFont font, TextAlignment align, DeviceRgb bg) {
        String txt = val == null ? "" : val.toString();
        return new Cell()
                .add(new Paragraph(txt).setFont(font).setFontSize(8))
                .setTextAlignment(align).setBackgroundColor(bg).setPadding(3);
    }

    private Cell celdaMonedaPDF(Object val, PdfFont font, DeviceRgb bg) {
        double num = val instanceof Number n ? n.doubleValue() : 0;
        return celdaTablaPDF(String.format("$%.2f", num), font, TextAlignment.RIGHT, bg);
    }

    private String stripHtmlPDF(String html) {
        if (html == null) return "";
        return html.replaceAll("<[^>]*>", "").trim();
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new ORDENCOMPRA().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
