
package com.mycompany.ocxrst.vistas;

import com.mycompany.ocxrst.IconoVentanaUtil;
import com.mycompany.ocxrst.config.AppConfig;
import java.io.File;
import java.io.FileInputStream;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author Maria Luisa Martinez
 */
public class INICIARSESION extends javax.swing.JFrame {

    /** Usuario que inició sesión actualmente */
    public static String usuarioActual = "";
    /** Nombre completo asociado al usuario autenticado */
    public static String nombreUsuarioActual = "";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(INICIARSESION.class.getName());

    /**
     * Creates new form PRINCIPAL
     */
    public INICIARSESION() {
        initComponents();
        IconoVentanaUtil.aplicar(this);
        setLocationRelativeTo(null); 
        java.awt.EventQueue.invokeLater(() -> jTextField1.requestFocusInWindow());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordField1.addActionListener(this::jPasswordField1ActionPerformed);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 190, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setDoubleBuffered(true);
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 190, -1));

        jButton1.setBackground(new java.awt.Color(0, 95, 131));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INICIA SESIÓN");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 120, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 95, 131));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("USUARIO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 200, 140, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 95, 131));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("CONTRASEÑA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 240, 140, 20));

        salir.setText("X");
        salir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        salir.addActionListener(this::salirActionPerformed);
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 20, 20));

        jLabel1.setIcon(IconoVentanaUtil.obtenerIconoSeguro("/com/mycompany/ocxrst/IMAGENES/Logo PDF2.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 260, 120));

        LOGO.setBackground(new java.awt.Color(0, 102, 102));
        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LOGO.setIcon(IconoVentanaUtil.obtenerIconoSeguro("/com/mycompany/ocxrst/IMAGENES/COPA.jpeg")); // NOI18N
        LOGO.setLabelFor(LOGO);
        LOGO.setDoubleBuffered(true);
        LOGO.setFocusCycleRoot(true);
        LOGO.setFocusTraversalPolicyProvider(true);
        LOGO.setOpaque(true);
        getContentPane().add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        autenticar();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void autenticar() {
        String usuario = jTextField1.getText();
        String contraseña = new String(jPasswordField1.getPassword());

        if (validarUsuarioExcel(usuario, contraseña)) {
            usuarioActual = usuario;
            nombreUsuarioActual = obtenerNombreUsuarioExcel(usuario, contraseña);
            String nombreMostrado = nombreUsuarioActual == null || nombreUsuarioActual.isBlank()
                    ? usuario
                    : nombreUsuarioActual;
            javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido " + nombreMostrado);

            PRINCIPAL ventana = new PRINCIPAL();
            ventana.setVisible(true);

            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        autenticar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        autenticar();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new INICIARSESION().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables



    public static String obtenerNombreUsuarioExcel(String usuario, String contraseña) {
        try {
            File archivo = AppConfig.resolveBaseFile("USUARIOS.xlsx");
            if (!archivo.exists()) {
                return "";
            }

            try (FileInputStream fis = new FileInputStream(archivo);
                 Workbook libro = new XSSFWorkbook(fis)) {
                return obtenerNombreUsuarioExcel(libro, usuario, contraseña);
            }
        } catch (Exception e) {
            e.printStackTrace();
            return "";
        }
    }

    public static String obtenerNombreUsuarioExcel(Workbook libro, String usuario, String contraseña) {
        if (libro == null) {
            return "";
        }

        Sheet hoja = libro.getSheetAt(0);
        for (int i = 1; i <= hoja.getLastRowNum(); i++) {
            Row fila = hoja.getRow(i);
            if (fila == null) {
                continue;
            }

            String userExcel = obtenerValorCelda(fila, 0);
            String passExcel = obtenerValorCelda(fila, 1);
            String nombreExcel = obtenerValorCelda(fila, 2);

            if (usuario.equals(userExcel) && contraseña.equals(passExcel)) {
                return nombreExcel;
            }
        }

        return "";
    }

    private static String obtenerValorCelda(Row fila, int columna) {
        if (fila == null) {
            return "";
        }
        Cell celda = fila.getCell(columna, Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);
        if (celda == null) {
            return "";
        }
        return celda.toString().trim();
    }

    public boolean validarUsuarioExcel(String usuario, String contraseña) {
        boolean encontrado = false;

        try {
            File archivo = AppConfig.resolveBaseFile("USUARIOS.xlsx");
            FileInputStream fis = new FileInputStream(archivo);
            Workbook libro = new XSSFWorkbook(fis);
            Sheet hoja = libro.getSheetAt(0);

            for (int i = 1; i <= hoja.getLastRowNum(); i++) {
                Row fila = hoja.getRow(i);

                if (fila != null) {
                    Cell celdaUsuario = fila.getCell(0, Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);
                    Cell celdaPass = fila.getCell(1, Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);

                    String userExcel = celdaUsuario == null ? "" : celdaUsuario.toString();
                    String passExcel = celdaPass == null ? "" : celdaPass.toString();

                    if (usuario.equals(userExcel) && contraseña.equals(passExcel)) {
                        encontrado = true;
                        break;
                    }
                }
            }

            libro.close();
            fis.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        return encontrado;
    }
}
