/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ocxrst.vistas;

import com.mycompany.ocxrst.IconoVentanaUtil;
import com.mycompany.ocxrst.config.AppConfig;
import com.mycompany.ocxrst.repository.ProveedorRepository;
import com.mycompany.ocxrst.service.ProveedorService;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Maria Luisa Martinez
 */
public class PROVEEDORES extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PROVEEDORES.class.getName());
    private static final String ORDENES_FILE_ABSOLUTE = AppConfig.registroCFile().getAbsolutePath();
    private static final String ORDENES_DETALLE_FILE_ABSOLUTE = AppConfig.intOrdenCompraFile().getAbsolutePath();
    private static final String[] ENCABEZADOS = ProveedorRepository.ENCABEZADOS;
    private final ProveedorRepository proveedorRepository = new ProveedorRepository();
    private int filaProveedorActual = -1;

    // Caché de proveedores para autocompletar: id -> "id | nombre"
    private final java.util.List<String[]> cacheProveedores = new java.util.ArrayList<>();
    private final javax.swing.JPopupMenu popupProveedores = new javax.swing.JPopupMenu();
    private boolean seleccionandoProveedor = false;

    /**
     * Creates new form PRINCIPAL
     */
    public PROVEEDORES() {
        initComponents();
        IconoVentanaUtil.aplicar(this);
        setLocationRelativeTo(null);
        asegurarArchivoProveedores();
        cargarCacheProveedores();
        configurarAutocompleteNombre();
        configurarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 95, 131));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROVEEDORES");

        jButton1.setBackground(new java.awt.Color(0, 95, 131));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CREAR");

        jButton2.setBackground(new java.awt.Color(0, 95, 131));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDITAR");

        jButton3.setBackground(java.awt.Color.WHITE);
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ELIMINAR");

        jButton6.setBackground(new java.awt.Color(0, 95, 131));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("< ATRAS");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jLabelId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelId.setText("ID:");

        jTextFieldId.setEditable(false);

        jLabel2.setText("NOMBRE O RAZÓN SOCIAL:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("RFC:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("TELÉFONO:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("CORREO:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("DIRECCIÓN:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("CONTACTO:");

        jButton4.setBackground(new java.awt.Color(0, 95, 131));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("HISTORIAL DE COMPRAS");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(jLabelId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldId)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(60, 60, 60))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(60, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        PRINCIPAL ventana = new PRINCIPAL();
        ventana.setVisible(true); // 👉 abre la nueva ventana
        
        this.dispose(); // 👉 cierra el login
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        mostrarHistorialCompras();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PROVEEDORES().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    private void configurarEventos() {
        jButton1.addActionListener(e -> crearProveedor());
        jButton2.addActionListener(e -> editarProveedor());
        jButton3.addActionListener(e -> alternarEstadoProveedor());
        restablecerIndicadorEstado();
    }//configurarEventos

    private void asegurarArchivoProveedores() {
        try {
            proveedorRepository.asegurarArchivoProveedores();
        } catch (IllegalStateException ex) {
            mostrarError("No se pudo preparar el archivo de proveedores.", ex);
        }
    }//asegurarArchivoProveedores

    private void crearProveedor() {
        if (!validarCamposBase()) {
            return;
        }

        String rfc = jTextField2.getText().trim();
        String idCreado = "";

        try {
            File archivo = obtenerArchivoProveedores();
            try (Workbook libro = cargarLibro(archivo)) {
                Sheet hoja = obtenerHojaProveedores(libro);
                asegurarEncabezados(hoja);

                if (buscarFilaProveedorPorRFC(hoja, rfc) >= 0) {
                    JOptionPane.showMessageDialog(this, "Ya existe un proveedor con ese RFC.");
                    return;
                }

                int nuevaFila = primeraFilaDisponible(hoja);
                Row fila = hoja.getRow(nuevaFila);
                if (fila == null) {
                    fila = hoja.createRow(nuevaFila);
                }

                idCreado = generarIdProveedor(hoja, jTextField1.getText().trim());
                escribirCelda(fila, 0, idCreado);
                guardarDatosPrincipalesEnFila(fila);
                completarValoresComercialesPorDefecto(fila);
                escribirCelda(fila, 11, "1");

                guardarLibro(libro, archivo);
                filaProveedorActual = nuevaFila;
                actualizarIndicadorEstado("1");
            }

            jTextFieldId.setText(idCreado);
            JOptionPane.showMessageDialog(this, "Proveedor creado.\nID asignado: " + idCreado + "\nEstado: ACTIVO (1)");
            limpiarFormulario(false);
            cargarCacheProveedores();
        } catch (IOException ex) {
            mostrarError("No se pudo crear el proveedor.", ex);
        }
    }//crearProveedor

    private void editarProveedor() {
        if (!validarCamposBase()) {
            return;
        }

        try {
            File archivo = obtenerArchivoProveedores();
            try (Workbook libro = cargarLibro(archivo)) {
                Sheet hoja = obtenerHojaProveedores(libro);
                asegurarEncabezados(hoja);

                int filaIndex = resolverFilaProveedor(hoja);
                if (filaIndex < 0) {
                    restablecerIndicadorEstado();
                    JOptionPane.showMessageDialog(this, "No se encontro un proveedor para editar. Usa BUSCAR primero.");
                    return;
                }

                String rfcForm = jTextField2.getText().trim();
                int filaMismoRFC = buscarFilaProveedorPorRFC(hoja, rfcForm);
                if (filaMismoRFC >= 0 && filaMismoRFC != filaIndex) {
                    JOptionPane.showMessageDialog(this, "El RFC ya pertenece a otro proveedor.");
                    return;
                }

                Row fila = hoja.getRow(filaIndex);
                if (fila == null) {
                    fila = hoja.createRow(filaIndex);
                }

                if (leerCelda(fila, 0).isEmpty()) {
                    escribirCelda(fila, 0, generarIdProveedor(hoja, jTextField1.getText().trim()));
                }
                guardarDatosPrincipalesEnFila(fila);
                completarValoresComercialesPorDefecto(fila);

                if (leerCelda(fila, 11).isEmpty()) {
                    escribirCelda(fila, 11, "1");
                } else {
                    escribirCelda(fila, 11, normalizarEstado(leerCelda(fila, 11)));
                }

                guardarLibro(libro, archivo);
                filaProveedorActual = filaIndex;
                actualizarIndicadorEstado(leerCelda(fila, 11));

                jTextFieldId.setText(leerCelda(fila, 0));
            }

            JOptionPane.showMessageDialog(this, "Proveedor actualizado correctamente.");
            cargarCacheProveedores();
        } catch (IOException ex) {
            mostrarError("No se pudo editar el proveedor.", ex);
        }
    }//editarProveedor

    private void alternarEstadoProveedor() {
        try {
            File archivo = obtenerArchivoProveedores();
            try (Workbook libro = cargarLibro(archivo)) {
                Sheet hoja = obtenerHojaProveedores(libro);
                asegurarEncabezados(hoja);

                int filaIndex = resolverFilaProveedor(hoja);
                if (filaIndex < 0) {
                    restablecerIndicadorEstado();
                    JOptionPane.showMessageDialog(this, "No se encontro un proveedor para activar/desactivar. Usa BUSCAR primero.");
                    return;
                }

                Row fila = hoja.getRow(filaIndex);
                if (fila == null) {
                    restablecerIndicadorEstado();
                    JOptionPane.showMessageDialog(this, "El registro encontrado esta vacio.");
                    return;
                }

                String estadoActual = normalizarEstado(leerCelda(fila, 11));
                String nuevoEstado = "1".equals(estadoActual) ? "0" : "1";
                escribirCelda(fila, 11, nuevoEstado);

                guardarLibro(libro, archivo);
                actualizarIndicadorEstado(nuevoEstado);

                filaProveedorActual = filaIndex;
            }
        } catch (IOException ex) {
            mostrarError("No se pudo cambiar el estado del proveedor.", ex);
        }
    }//alternarEstadoProveedor

    private void buscarProveedor() {
        String nombre = jTextField1.getText().trim();
        String rfc = jTextField2.getText().trim();

        if (nombre.isEmpty() && rfc.isEmpty()) {
            restablecerIndicadorEstado();
            JOptionPane.showMessageDialog(this, "Ingresa NOMBRE O RAZÓN SOCIAL, o RFC para buscar.");
            return;
        }

        try {
            File archivo = obtenerArchivoProveedores();
            try (Workbook libro = cargarLibro(archivo)) {
                Sheet hoja = obtenerHojaProveedores(libro);
                asegurarEncabezados(hoja);

                int filaIndex = -1;
                if (!nombre.isEmpty()) {
                    filaIndex = buscarFilaProveedorPorNombre(hoja, nombre);
                }
                if (filaIndex < 0 && !rfc.isEmpty()) {
                    filaIndex = buscarFilaProveedorPorRFC(hoja, rfc);
                }

                if (filaIndex < 0) {
                    filaProveedorActual = -1;
                    restablecerIndicadorEstado();
                    JOptionPane.showMessageDialog(this, "No se encontro un proveedor con los datos capturados.");
                    return;
                }

                Row fila = hoja.getRow(filaIndex);
                if (fila == null) {
                    filaProveedorActual = -1;
                    restablecerIndicadorEstado();
                    JOptionPane.showMessageDialog(this, "El registro encontrado esta vacio.");
                    return;
                }

                cargarFilaEnFormulario(fila);
                filaProveedorActual = filaIndex;

                String estado = normalizarEstado(leerCelda(fila, 11));
                actualizarIndicadorEstado(estado);
            }
        } catch (IOException ex) {
            restablecerIndicadorEstado();
            mostrarError("No se pudo buscar el proveedor.", ex);
        }
    }//buscarProveedor

    private void mostrarHistorialCompras() {
        String idProveedor = jTextFieldId.getText().trim();

        java.util.List<Object[]> filas = new java.util.ArrayList<>();
        double sumaTotal = 0;
        double sumaAbonado = 0;
        String simboloMoneda = "$";
        File archivoOrdenes = new File(ORDENES_FILE_ABSOLUTE);
        if (archivoOrdenes.exists()) {
            try (FileInputStream fis = new FileInputStream(archivoOrdenes);
                 Workbook libro = new XSSFWorkbook(fis)) {
                Sheet hoja = libro.getSheetAt(0);
                for (Row row : hoja) {
                    if (row.getRowNum() == 0) {
                        continue;
                    }
                    String idFila = leerCelda(row, 4);
                    if (!idProveedor.isEmpty() && !idProveedor.equalsIgnoreCase(idFila)) {
                        continue;
                    }

                    String noOrden = leerCelda(row, 0);
                    java.util.Date fecha = leerFechaCelda(row, 1);
                    String cotizacion = leerCelda(row, 3);
                    String solicitante = leerCelda(row, 6);
                    String total = leerCelda(row, 21);
                    String abonado = leerCelda(row, 22);
                    String estatus = leerCelda(row, 23);
                    String pendiente = calcularPendientePago(total, abonado);
                    sumaTotal += parseMonto(total);
                    sumaAbonado += parseMonto(abonado);
                    if (!total.isEmpty()) {
                        simboloMoneda = obtenerSimboloMoneda(total);
                    }

                    String fechaTexto = "";
                    String diasTexto = "";
                    if (fecha != null) {
                        java.time.LocalDate fechaOrden = fecha.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                        fechaTexto = fechaOrden.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                        diasTexto = String.valueOf(java.time.temporal.ChronoUnit.DAYS.between(fechaOrden, java.time.LocalDate.now()));
                    }

                    filas.add(new Object[]{idFila, noOrden, fechaTexto, cotizacion, solicitante, total, abonado, pendiente, diasTexto, estatus});
                }
            } catch (Exception ex) {
                mostrarError("No se pudo leer el historial de ordenes de compra.", ex);
                return;
            }
        }

        String[] columnas = {
            "ID PROVEEDOR", "NO. ORDEN", "FECHA", "COTIZACI\u00d3N", "SOLICITANTE", "TOTAL", "ABONADO", "PENDIENTE POR PAGAR", "D\u00cdAS TRANSCURRIDOS", "ESTATUS"
        };
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        for (Object[] fila : filas) {
            modelo.addRow(fila);
        }

        javax.swing.JTable tabla = new javax.swing.JTable(modelo);
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        configurarColumnaNoOrdenComoEnlace(tabla);
        ajustarAnchoColumnas(tabla);

        javax.swing.JLabel etiquetaTotal = new javax.swing.JLabel(
                (idProveedor.isEmpty() ? "Total de compras: " : "Total de compras del proveedor: ") + filas.size());
        etiquetaTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 4, 8));

        javax.swing.JPanel panelEncabezado = new javax.swing.JPanel();
        panelEncabezado.setLayout(new javax.swing.BoxLayout(panelEncabezado, javax.swing.BoxLayout.Y_AXIS));
        panelEncabezado.add(etiquetaTotal);

        if (!idProveedor.isEmpty()) {
            javax.swing.JLabel etiquetaSumaTotal = new javax.swing.JLabel(
                    String.format("Total de todas las órdenes: %s %,.2f", simboloMoneda, sumaTotal));
            etiquetaSumaTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 4, 8));
            panelEncabezado.add(etiquetaSumaTotal);

            javax.swing.JLabel etiquetaSumaAbonado = new javax.swing.JLabel(
                    String.format("Total abonado: %s %,.2f", simboloMoneda, sumaAbonado));
            etiquetaSumaAbonado.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 8, 8));
            panelEncabezado.add(etiquetaSumaAbonado);
        }

        javax.swing.JButton botonAbonar = new javax.swing.JButton("ABONAR");
        botonAbonar.addActionListener(e -> registrarAbono(tabla));
        javax.swing.JPanel panelBoton = new javax.swing.JPanel(new java.awt.BorderLayout());
        panelBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 4, 8));
        panelBoton.add(botonAbonar, java.awt.BorderLayout.NORTH);

        javax.swing.JPanel panelSuperior = new javax.swing.JPanel(new java.awt.BorderLayout());
        panelSuperior.add(panelEncabezado, java.awt.BorderLayout.WEST);
        panelSuperior.add(panelBoton, java.awt.BorderLayout.EAST);

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout());
        panel.add(panelSuperior, java.awt.BorderLayout.NORTH);
        panel.add(new javax.swing.JScrollPane(tabla), java.awt.BorderLayout.CENTER);

        int anchoTotal = tabla.getColumnModel().getTotalColumnWidth() + 60;
        int altoTotal = (tabla.getRowCount() + 1) * tabla.getRowHeight() + 120;
        java.awt.Dimension pantalla = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int anchoPanel = Math.max(1200, Math.min(anchoTotal, pantalla.width - 80));
        int altoPanel = Math.max(600, Math.min(altoTotal, pantalla.height - 80));
        panel.setPreferredSize(new java.awt.Dimension(anchoPanel, altoPanel));

        javax.swing.JDialog dialogo = new javax.swing.JDialog(this,
                idProveedor.isEmpty() ? "Historial de \u00d3rdenes de Compra - Todos los proveedores"
                        : "Historial de \u00d3rdenes de Compra - " + idProveedor,
                true);
        dialogo.getContentPane().add(panel);
        dialogo.setResizable(true);
        dialogo.pack();
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }//mostrarHistorialCompras

    private void registrarAbono(javax.swing.JTable tabla) {
        int filaSeleccionada = tabla.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una orden de la tabla primero.");
            return;
        }

        String noOrden = String.valueOf(tabla.getValueAt(filaSeleccionada, 1)).trim();
        String totalTexto = String.valueOf(tabla.getValueAt(filaSeleccionada, 5)).trim();
        String abonadoTexto = String.valueOf(tabla.getValueAt(filaSeleccionada, 6)).trim();

        double totalNumero = parseMonto(totalTexto);
        double abonadoActual = parseMonto(abonadoTexto);
        double pendiente = totalNumero - abonadoActual;

        if (pendiente <= 0) {
            JOptionPane.showMessageDialog(this, "Esta orden ya est\u00e1 totalmente abonada.");
            return;
        }

        String simbolo = obtenerSimboloMoneda(totalTexto);
        String entrada = JOptionPane.showInputDialog(this,
                String.format("Pendiente por pagar: %s %,.2f%nCaptura la cantidad a abonar:", simbolo, pendiente));
        if (entrada == null) {
            return;
        }

        double monto = parseMonto(entrada);
        if (monto <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad a abonar debe ser mayor a 0.");
            return;
        }
        if (monto > pendiente + 0.001) {
            JOptionPane.showMessageDialog(this,
                    String.format("La cantidad no puede exceder el pendiente (%s %,.2f).", simbolo, pendiente));
            return;
        }

        double nuevoAbonado = abonadoActual + monto;
        File archivoOrdenes = new File(ORDENES_FILE_ABSOLUTE);
        try (FileInputStream fis = new FileInputStream(archivoOrdenes);
             Workbook libro = new XSSFWorkbook(fis)) {
            Sheet hoja = libro.getSheetAt(0);
            boolean actualizado = false;
            for (Row row : hoja) {
                if (row.getRowNum() == 0) {
                    continue;
                }
                if (noOrden.equalsIgnoreCase(leerCelda(row, 0))) {
                    escribirCelda(row, 22, String.format("%s %,.2f", simbolo, nuevoAbonado));
                    actualizado = true;
                    break;
                }
            }
            if (!actualizado) {
                JOptionPane.showMessageDialog(this, "No se encontr\u00f3 la orden en el archivo.");
                return;
            }
            try (FileOutputStream fos = new FileOutputStream(archivoOrdenes)) {
                libro.write(fos);
            }
        } catch (Exception ex) {
            mostrarError("No se pudo registrar el abono.", ex);
            return;
        }

        JOptionPane.showMessageDialog(this, "Abono registrado correctamente.");
        javax.swing.SwingUtilities.getWindowAncestor(tabla).dispose();
        mostrarHistorialCompras();
    }//registrarAbono

    private void configurarColumnaNoOrdenComoEnlace(javax.swing.JTable tabla) {
        final int columnaNoOrden = 1;
        javax.swing.table.DefaultTableCellRenderer rendererEnlace = new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable t, Object valor,
                    boolean seleccionado, boolean foco, int fila, int columna) {
                java.awt.Component comp = super.getTableCellRendererComponent(t, valor, seleccionado, foco, fila, columna);
                java.util.Map<java.awt.font.TextAttribute, Object> atributos = new java.util.HashMap<>(comp.getFont().getAttributes());
                atributos.put(java.awt.font.TextAttribute.UNDERLINE, java.awt.font.TextAttribute.UNDERLINE_ON);
                comp.setFont(comp.getFont().deriveFont(atributos));
                if (!seleccionado) {
                    comp.setForeground(new java.awt.Color(0, 90, 200));
                }
                return comp;
            }
        };
        tabla.getColumnModel().getColumn(columnaNoOrden).setCellRenderer(rendererEnlace);

        tabla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int columna = tabla.columnAtPoint(e.getPoint());
                tabla.setCursor(columna == columnaNoOrden
                        ? java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR)
                        : java.awt.Cursor.getDefaultCursor());
            }
        });

        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int fila = tabla.rowAtPoint(e.getPoint());
                int columna = tabla.columnAtPoint(e.getPoint());
                if (fila >= 0 && columna == columnaNoOrden) {
                    mostrarDetalleOrden(String.valueOf(tabla.getValueAt(fila, columnaNoOrden)).trim());
                }
            }
        });
    }//configurarColumnaNoOrdenComoEnlace

    private void mostrarDetalleOrden(String noOrden) {
        if (noOrden.isEmpty()) {
            return;
        }

        java.util.Map<String, String> datos = new java.util.LinkedHashMap<>();
        File archivoOrdenes = new File(ORDENES_FILE_ABSOLUTE);
        if (archivoOrdenes.exists()) {
            try (FileInputStream fis = new FileInputStream(archivoOrdenes);
                 Workbook libro = new XSSFWorkbook(fis)) {
                Sheet hoja = libro.getSheetAt(0);
                for (Row row : hoja) {
                    if (row.getRowNum() == 0) {
                        continue;
                    }
                    if (!noOrden.equalsIgnoreCase(leerCelda(row, 0))) {
                        continue;
                    }
                    datos.put("NO. ORDEN", leerCelda(row, 0));
                    datos.put("FECHA", formatearFechaCelda(leerFechaCelda(row, 1)));
                    datos.put("DOCUMENTO", leerCelda(row, 2));
                    datos.put("COTIZACI\u00d3N", leerCelda(row, 3));
                    datos.put("ID PROVEEDOR", leerCelda(row, 4));
                    datos.put("CFDI", leerCelda(row, 5));
                    datos.put("SOLICITANTE", leerCelda(row, 6));
                    datos.put("PROYECTO", leerCelda(row, 7));
                    datos.put("PAGO", leerCelda(row, 8));
                    datos.put("FORMA DE PAGO", leerCelda(row, 9));
                    datos.put("M\u00c9TODO DE PAGO", leerCelda(row, 10));
                    datos.put("ENTREGA INICIO", leerCelda(row, 11));
                    datos.put("ENTREGA FINAL", leerCelda(row, 12));
                    datos.put("DESCUENTO", leerCelda(row, 13));
                    datos.put("IVA", leerCelda(row, 14));
                    datos.put("ELABOR\u00d3", leerCelda(row, 15));
                    datos.put("AUTORIZ\u00d3", leerCelda(row, 16));
                    datos.put("MONEDA", leerCelda(row, 17));
                    datos.put("TIPO DE CAMBIO", leerCelda(row, 18));
                    datos.put("SUBTOTAL", leerCelda(row, 19));
                    datos.put("IVA IMPORTE", leerCelda(row, 20));
                    datos.put("TOTAL", leerCelda(row, 21));
                    datos.put("ABONADO", leerCelda(row, 22));
                    datos.put("PENDIENTE POR PAGAR", calcularPendientePago(leerCelda(row, 21), leerCelda(row, 22)));
                    datos.put("ESTATUS", leerCelda(row, 23));
                    break;
                }
            } catch (Exception ex) {
                mostrarError("No se pudo leer la orden de compra.", ex);
                return;
            }
        }

        if (datos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontr\u00f3 informaci\u00f3n de la orden " + noOrden + ".");
            return;
        }

        javax.swing.JPanel panelDatos = new javax.swing.JPanel(new java.awt.GridLayout(0, 2, 8, 4));
        panelDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        for (java.util.Map.Entry<String, String> dato : datos.entrySet()) {
            panelDatos.add(new javax.swing.JLabel(dato.getKey() + ":"));
            javax.swing.JLabel valor = new javax.swing.JLabel(dato.getValue().isEmpty() ? "-" : dato.getValue());
            valor.setFont(valor.getFont().deriveFont(java.awt.Font.BOLD));
            panelDatos.add(valor);
        }

        String[] columnasProductos = {"C\u00d3DIGO", "DESCRIPCI\u00d3N", "UNIDAD", "CANTIDAD", "PRECIO", "IMPORTE"};
        javax.swing.table.DefaultTableModel modeloProductos = new javax.swing.table.DefaultTableModel(columnasProductos, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };

        File archivoDetalle = new File(ORDENES_DETALLE_FILE_ABSOLUTE);
        if (archivoDetalle.exists()) {
            try (FileInputStream fis = new FileInputStream(archivoDetalle);
                 Workbook libro = new XSSFWorkbook(fis)) {
                Sheet hoja = libro.getSheetAt(0);
                for (Row row : hoja) {
                    if (row.getRowNum() == 0) {
                        continue;
                    }
                    if (noOrden.equalsIgnoreCase(leerCelda(row, 0))) {
                        modeloProductos.addRow(new Object[]{
                            leerCelda(row, 1), leerCelda(row, 2), leerCelda(row, 3),
                            leerCelda(row, 4), leerCelda(row, 5), leerCelda(row, 6)
                        });
                    }
                }
            } catch (Exception ex) {
                mostrarError("No se pudo leer los productos de la orden.", ex);
            }
        }

        javax.swing.JTable tablaProductos = new javax.swing.JTable(modeloProductos);
        tablaProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaProductos.setRowHeight(24);
        tablaProductos.setGridColor(new java.awt.Color(220, 220, 220));
        tablaProductos.setShowGrid(true);
        tablaProductos.getTableHeader().setFont(tablaProductos.getTableHeader().getFont().deriveFont(java.awt.Font.BOLD));
        ajustarAnchoColumnas(tablaProductos);

        javax.swing.JPanel panelProductos = new javax.swing.JPanel(new java.awt.BorderLayout());
        panelProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("PRODUCTOS"));
        javax.swing.JScrollPane scrollProductos = new javax.swing.JScrollPane(tablaProductos);
        scrollProductos.setPreferredSize(new java.awt.Dimension(700, 220));
        panelProductos.add(scrollProductos, java.awt.BorderLayout.CENTER);

        javax.swing.JPanel panelContenido = new javax.swing.JPanel(new java.awt.BorderLayout(10, 10));
        panelContenido.add(new javax.swing.JScrollPane(panelDatos), java.awt.BorderLayout.NORTH);
        panelContenido.add(panelProductos, java.awt.BorderLayout.CENTER);
        panelContenido.setPreferredSize(new java.awt.Dimension(900, 700));

        javax.swing.JDialog dialogo = new javax.swing.JDialog(this, "Orden de Compra No. " + noOrden, true);
        dialogo.getContentPane().add(panelContenido);
        dialogo.setResizable(true);
        dialogo.pack();
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }//mostrarDetalleOrden

    private String formatearFechaCelda(java.util.Date fecha) {
        if (fecha == null) {
            return "";
        }
        return fecha.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate()
                .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));
    }//formatearFechaCelda

    private void ajustarAnchoColumnas(javax.swing.JTable tabla) {
        javax.swing.table.TableColumnModel modeloColumnas = tabla.getColumnModel();
        for (int columna = 0; columna < tabla.getColumnCount(); columna++) {
            javax.swing.table.TableColumn tableColumn = modeloColumnas.getColumn(columna);
            javax.swing.table.TableCellRenderer rendererEncabezado = tabla.getTableHeader().getDefaultRenderer();
            int ancho = rendererEncabezado
                    .getTableCellRendererComponent(tabla, tableColumn.getHeaderValue(), false, false, 0, columna)
                    .getPreferredSize().width;

            for (int fila = 0; fila < tabla.getRowCount(); fila++) {
                javax.swing.table.TableCellRenderer renderer = tabla.getCellRenderer(fila, columna);
                int anchoCelda = tabla.prepareRenderer(renderer, fila, columna).getPreferredSize().width;
                ancho = Math.max(ancho, anchoCelda);
            }

            tableColumn.setPreferredWidth(ancho + 16);
        }
    }//ajustarAnchoColumnas

    private String calcularPendientePago(String total, String abonado) {
        double totalNumero = parseMonto(total);
        double abonadoNumero = parseMonto(abonado);
        double pendiente = totalNumero - abonadoNumero;
        String simbolo = obtenerSimboloMoneda(total);
        return String.format("%s %,.2f", simbolo, pendiente);
    }//calcularPendientePago

    private double parseMonto(String texto) {
        if (texto == null) {
            return 0;
        }
        String limpio = texto.replaceAll("[^0-9.\\-]", "");
        if (limpio.isEmpty()) {
            return 0;
        }
        try {
            return Double.parseDouble(limpio);
        } catch (NumberFormatException ex) {
            return 0;
        }
    }//parseMonto

    private String obtenerSimboloMoneda(String texto) {
        if (texto == null) {
            return "$";
        }
        String simbolo = texto.replaceAll("[0-9.,\\s]", "").trim();
        return simbolo.isEmpty() ? "$" : simbolo;
    }//obtenerSimboloMoneda

    private java.util.Date leerFechaCelda(Row row, int columna) {
        Cell celda = row.getCell(columna, Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);
        if (celda == null) {
            return null;
        }
        try {
            if (celda.getCellType() == org.apache.poi.ss.usermodel.CellType.NUMERIC
                    && org.apache.poi.ss.usermodel.DateUtil.isCellDateFormatted(celda)) {
                return celda.getDateCellValue();
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.WARNING, "No se pudo leer fecha de orden", ex);
        }
        return null;
    }//leerFechaCelda

    private boolean validarCamposBase() {
        if (jTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NOMBRE O RAZON SOCIAL es obligatorio.");
            return false;
        }
        if (jTextField2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "RFC es obligatorio.");
            return false;
        }
        return true;
    }//validarCamposBase

    private int resolverFilaProveedor(Sheet hoja) {
        if (filaProveedorActual > 0 && filaProveedorActual <= hoja.getLastRowNum()) {
            Row fila = hoja.getRow(filaProveedorActual);
            if (fila != null) {
                String rfcCapturado = jTextField2.getText().trim();
                String rfcFila = leerCelda(fila, 2);
                if (rfcCapturado.isEmpty() || rfcCapturado.equalsIgnoreCase(rfcFila)) {
                    return filaProveedorActual;
                }
            }
        }

        String rfc = jTextField2.getText().trim();
        if (!rfc.isEmpty()) {
            int filaPorRFC = buscarFilaProveedorPorRFC(hoja, rfc);
            if (filaPorRFC >= 0) {
                return filaPorRFC;
            }
        }

        String nombre = jTextField1.getText().trim();
        if (!nombre.isEmpty()) {
            int filaPorNombre = buscarFilaProveedorPorNombre(hoja, nombre);
            if (filaPorNombre >= 0) {
                return filaPorNombre;
            }
        }

        return -1;
    }//resolverFilaProveedor

    private void guardarDatosPrincipalesEnFila(Row fila) {
        escribirCelda(fila, 1, jTextField1.getText().trim());
        escribirCelda(fila, 2, jTextField2.getText().trim());
        escribirCelda(fila, 3, jTextField3.getText().trim());
        escribirCelda(fila, 4, jTextField4.getText().trim());
        escribirCelda(fila, 5, jTextField5.getText().trim());
        escribirCelda(fila, 6, jTextField6.getText().trim());
    }//guardarDatosPrincipalesEnFila

    private void completarValoresComercialesPorDefecto(Row fila) {
        if (leerCelda(fila, 7).isEmpty()) {
            escribirCelda(fila, 7, "CONTADO");
        }
        if (leerCelda(fila, 8).isEmpty()) {
            escribirCelda(fila, 8, "PUE(PAGO EN UNA SOLA EXHIBICION)");
        }
        if (leerCelda(fila, 9).isEmpty()) {
            escribirCelda(fila, 9, "De 3 a 5 dias");
        }
        if (leerCelda(fila, 10).isEmpty()) {
            escribirCelda(fila, 10, "Transferencia Electronica Fondos");
        }
    }//completarValoresComercialesPorDefecto

    private void cargarFilaEnFormulario(Row fila) {
        jTextFieldId.setText(leerCelda(fila, 0));
        jTextField1.setText(leerCelda(fila, 1));
        jTextField2.setText(leerCelda(fila, 2));
        jTextField3.setText(leerCelda(fila, 3));
        jTextField4.setText(leerCelda(fila, 4));
        jTextField5.setText(leerCelda(fila, 5));
        jTextField6.setText(leerCelda(fila, 6));
    }//cargarFilaEnFormulario

    private void limpiarFormulario(boolean conservarNombre) {
        jTextFieldId.setText("");
        if (!conservarNombre) {
            jTextField1.setText("");
        }
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        filaProveedorActual = -1;
        restablecerIndicadorEstado();
    }//limpiarFormulario

    private void configurarAutocompleteNombre() {
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (!e.isTemporary()) {
                    popupProveedores.setVisible(false);
                    if (jTextField1.getText().trim().isEmpty()) {
                        limpiarFormulario(false);
                    }
                }
            }
        });

        jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filtrarProveedoresNombre(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filtrarProveedoresNombre(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filtrarProveedoresNombre(); }
        });
    }//configurarAutocompleteNombre

    private void cargarCacheProveedores() {
        cacheProveedores.clear();
        try {
            File archivo = obtenerArchivoProveedores();
            try (Workbook libro = cargarLibro(archivo)) {
                Sheet hoja = obtenerHojaProveedores(libro);
                for (int fila = 1; fila <= hoja.getLastRowNum(); fila++) {
                    Row row = hoja.getRow(fila);
                    if (row == null) {
                        continue;
                    }
                    String id = leerCelda(row, 0);
                    String nombre = leerCelda(row, 1);
                    if (!nombre.isEmpty()) {
                        cacheProveedores.add(new String[]{id, nombre});
                    }
                }
            }
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.WARNING, "No se pudo cargar cache de proveedores", ex);
        }
    }//cargarCacheProveedores

    private void filtrarProveedoresNombre() {
        if (seleccionandoProveedor) {
            return;
        }
        String texto = jTextField1.getText().trim().toLowerCase();
        popupProveedores.setVisible(false);
        popupProveedores.removeAll();
        if (texto.isEmpty()) {
            return;
        }

        int count = 0;
        for (String[] prov : cacheProveedores) {
            if (prov[1].toLowerCase().contains(texto)) {
                String etiqueta = prov[0] + "  |  " + prov[1];
                javax.swing.JMenuItem item = new javax.swing.JMenuItem(etiqueta);
                final String nombre = prov[1];
                item.addActionListener(ev -> {
                    seleccionandoProveedor = true;
                    popupProveedores.setVisible(false);
                    jTextField1.setText(nombre);
                    buscarProveedor();
                    seleccionandoProveedor = false;
                });
                popupProveedores.add(item);
                if (++count == 10) {
                    break;
                }
            }
        }

        if (count > 0) {
            popupProveedores.show(jTextField1, 0, jTextField1.getHeight());
            jTextField1.requestFocusInWindow();
        }
    }//filtrarProveedoresNombre

    private int buscarFilaProveedorPorId(Sheet hoja, String id) {
        for (int fila = 1; fila <= hoja.getLastRowNum(); fila++) {
            Row row = hoja.getRow(fila);
            if (row == null) {
                continue;
            }
            String idActual = leerCelda(row, 0);
            if (id.equalsIgnoreCase(idActual)) {
                return fila;
            }
        }
        return -1;
    }//buscarFilaProveedorPorId

    private int buscarFilaProveedorPorNombre(Sheet hoja, String nombre) {
        for (int fila = 1; fila <= hoja.getLastRowNum(); fila++) {
            Row row = hoja.getRow(fila);
            if (row == null) {
                continue;
            }
            String nombreActual = leerCelda(row, 1);
            if (nombre.equalsIgnoreCase(nombreActual)) {
                return fila;
            }
        }
        return -1;
    }//buscarFilaProveedorPorNombre

    private int buscarFilaProveedorPorRFC(Sheet hoja, String rfc) {
        for (int fila = 1; fila <= hoja.getLastRowNum(); fila++) {
            Row row = hoja.getRow(fila);
            if (row == null) {
                continue;
            }
            String rfcActual = leerCelda(row, 2);
            if (rfc.equalsIgnoreCase(rfcActual)) {
                return fila;
            }
        }
        return -1;
    }//buscarFilaProveedorPorRFC

    private int primeraFilaDisponible(Sheet hoja) {
        for (int fila = 1; fila <= hoja.getLastRowNum(); fila++) {
            Row row = hoja.getRow(fila);
            if (row == null || leerCelda(row, 0).isEmpty()) {
                return fila;
            }
        }
        return hoja.getLastRowNum() + 1;
    }//primeraFilaDisponible

    private String generarIdProveedor(Sheet hoja, String nombreProveedor) {
        String base = nombreProveedor == null ? "" : nombreProveedor.replaceAll("[^A-Za-z0-9]", "").toLowerCase();
        if (base.isEmpty()) {
            base = "prov";
        }

        if (base.length() > 4) {
            base = base.substring(0, 4);
        }

        while (base.length() < 4) {
            base = base + "x";
        }

        for (int i = 1; i <= 999; i++) {
            String sufijo = i <= 99 ? String.format("%02d", i) : String.valueOf(i);
            String candidato = base + sufijo;
            if (buscarFilaProveedorPorId(hoja, candidato) < 0) {
                return candidato;
            }
        }

        return base + System.currentTimeMillis();
    }//generarIdProveedor

    private boolean asegurarEncabezados(Sheet hoja) {
        return proveedorRepository.asegurarEncabezados(hoja);
    }//asegurarEncabezados

    private Sheet obtenerHojaProveedores(Workbook libro) {
        return proveedorRepository.obtenerHojaProveedores(libro);
    }//obtenerHojaProveedores

    private Workbook cargarLibro(File archivo) throws IOException {
        return proveedorRepository.cargarLibro(archivo);
    }//cargarLibro

    private void guardarLibro(Workbook libro, File archivo) throws IOException {
        proveedorRepository.guardarLibro(libro, archivo);
    }//guardarLibro

    private File obtenerArchivoProveedores() {
        return proveedorRepository.obtenerArchivoProveedores();
    }//obtenerArchivoProveedores

    private String leerCelda(Row fila, int columna) {
        return proveedorRepository.leerCelda(fila, columna);
    }//leerCelda

    private void escribirCelda(Row fila, int columna, String valor) {
        proveedorRepository.escribirCelda(fila, columna, valor);
    }//escribirCelda

    private String normalizarEstado(String valor) {
        return ProveedorService.normalizarEstado(valor);
    }//normalizarEstado

    private void actualizarIndicadorEstado(String estado) {
        String estadoNormalizado = normalizarEstado(estado);
        jButton3.setBackground(java.awt.Color.WHITE);
        if ("1".equals(estadoNormalizado)) {
            jButton3.setText("DESACTIVAR (ACTIVO)");
            jButton3.setForeground(new java.awt.Color(0, 120, 0));
            jButton3.setToolTipText("Estado actual: ACTIVO (1)");
            return;
        }

        jButton3.setText("ACTIVAR (INACTIVO)");
        jButton3.setForeground(new java.awt.Color(180, 0, 0));
        jButton3.setToolTipText("Estado actual: INACTIVO (0)");
    }//actualizarIndicadorEstado

    private void restablecerIndicadorEstado() {
        jButton3.setText("ACTIVAR/DESACTIVAR");
        jButton3.setBackground(java.awt.Color.WHITE);
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setToolTipText("Estado actual: sin seleccionar");
    }//restablecerIndicadorEstado

    private void mostrarError(String mensajeUsuario, Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, mensajeUsuario, ex);
        JOptionPane.showMessageDialog(this, mensajeUsuario + "\nDetalle tecnico: " + ex.getMessage());
    }//mostrarError
}
